### ISSUE TITLE
Different approach

### ISSUE THREAD

**Issue by deakjahn** [dnfield/dart_path_parsing#2]
A different parsing class that I wrote and use, if you happen to be interested. Nothing to do with Chromium or similar, just a straightforward implementation of the specification with a plain old recursive descent parser.

Although it originally depended on https://github.com/dart-lang/string_scanner, it really only uses very few functions, so I simply copied those in the end, without depending on a separate package.

If you check out the whitespace-comma combo, it's more lenient than the original spec, on purpose. You could simply re-use the definition there but I can't see the point, this isn't about validation but consumption.

Also note that, while Skia (dart:ui) has obvious support for both absolute and relative co-ordinates, we have to keep track of the current and last control points because of the smooth curves, so I only used the absolute functions with the values I calculate, anyway. By the way, both smooth ones are supported, of course, and it's simpler than the Chromium approach, actually. No need for the complex arc-to-curve solution, either, because Skia supports it directly and perfectly.

Function names intentionally follow the specification, even if the IDE complains that this doesn't comply with the established Dart code style.

I don't really know what you would want to do with it, I feel this is a much cleaner approach than your (Chromium's) original one, but... :-))

    // https://www.w3.org/TR/SVG/paths.html#PathDataBNF
    class SvgPath {
      final String svg;
    
      SvgPath(this.svg);
    
      _StringScanner _scanner;
      Path _path;
      RegExp WHITESPACE = RegExp(r"\s*");
      RegExp COMMA_WHITESPACE = RegExp(r"[\s,]+");
      RegExp COMMAND = RegExp("[mMzZlLhHvVcCsSqQtTaA]");
      RegExp COORDINATE = RegExp(r"[+-]?(\d*\.\d+|\d+)");
      RegExp NUMBER = RegExp(r"\d*\.\d+|\d+");
      RegExp FLAG = RegExp("[01]");
      double _x = 0, _y = 0;
      double _controlX = 0, _controlY = 0;
      double _startX = 0, _startY = 0;
    
      Path parse() {
        if (svg == null) return null;
        if (svg.isEmpty) return Path();
    
        _path = Path();
        _scanner = _StringScanner(svg);
        _svg_path();
        return _path;
      }
    
      void _svg_path() {
        _scanner.scan(WHITESPACE);
        while (!_scanner.isDone) {
          _scanner.expect(COMMAND);
          switch (_scanner.lastMatch[0]) {
            case 'M':
              _moveto(true);
              break;
            case 'm':
              _moveto(false);
              break;
            case 'Z':
            case 'z':
              _closepath();
              break;
            case 'L':
              _lineto(true);
              break;
            case 'l':
              _lineto(false);
              break;
            case 'H':
              _horizontal_lineto(true);
              break;
            case 'h':
              _horizontal_lineto(false);
              break;
            case 'V':
              _vertical_lineto(true);
              break;
            case 'v':
              _vertical_lineto(false);
              break;
            case 'C':
              _curveto(true);
              break;
            case 'c':
              _curveto(false);
              break;
            case 'S':
              _smooth_curveto(true);
              break;
            case 's':
              _smooth_curveto(false);
              break;
            case 'Q':
              _quadratic_bezier_curveto(true);
              break;
            case 'q':
              _quadratic_bezier_curveto(false);
              break;
            case 'T':
              _smooth_quadratic_bezier_curveto(true);
              break;
            case 't':
              _smooth_quadratic_bezier_curveto(false);
              break;
            case 'A':
              _elliptical_arc(true);
              break;
            case 'a':
              _elliptical_arc(false);
              break;
            default:
              throw FormatException('command');
          }
        }
      }
    
      void _moveto(bool absolute) {
        _scanner.scan(WHITESPACE);
        for (final pair in _coordinate_pair_sequence()) {
          _x = (absolute) ? pair.x : _x + pair.x;
          _y = (absolute) ? pair.y : _y + pair.y;
          _path.moveTo(
            _startX = _controlX = _x,
            _startY = _controlY = _y,
          );
        }
      }
    
      void _closepath() {
        _scanner.scan(WHITESPACE);
        _x = _controlX = _startX;
        _y = _controlY = _startY;
        _path.close();
      }
    
      void _lineto(bool absolute) {
        _scanner.scan(WHITESPACE);
        for (final pair in _coordinate_pair_sequence()) {
          _x = (absolute) ? pair.x : _x + pair.x;
          _y = (absolute) ? pair.y : _y + pair.y;
          _path.lineTo(
            _controlX = _x,
            _controlY = _y,
          );
        }
      }
    
      void _horizontal_lineto(bool absolute) {
        _scanner.scan(WHITESPACE);
        for (double x in _coordinate_sequence()) {
          _x = (absolute) ? x : _x + x;
          _path.lineTo(
            _controlX = _x,
            _controlY = _y,
          );
        }
      }
    
      void _vertical_lineto(bool absolute) {
        _scanner.scan(WHITESPACE);
        for (double y in _coordinate_sequence()) {
          _y = (absolute) ? y : _y + y;
          _path.lineTo(
            _controlX = _x,
            _controlY = _y,
          );
        }
      }
    
      void _curveto(bool absolute) {
        _scanner.scan(WHITESPACE);
        for (final triplet in _curveto_coordinate_sequence()) {
          double x1 = (absolute) ? triplet[0].x : _x + triplet[0].x;
          double y1 = (absolute) ? triplet[0].y : _y + triplet[0].y;
          double x2 = (absolute) ? triplet[1].x : _x + triplet[1].x;
          double y2 = (absolute) ? triplet[1].y : _y + triplet[1].y;
          _x = (absolute) ? triplet[2].x : _x + triplet[2].x;
          _y = (absolute) ? triplet[2].y : _y + triplet[2].y;
          _path.cubicTo(
            x1,
            y1,
            _controlX = x2,
            _controlY = y2,
            _x,
            _y,
          );
        }
      }
    
      void _smooth_curveto(bool absolute) {
        _scanner.scan(WHITESPACE);
        for (final doublet in _smooth_curveto_coordinate_sequence()) {
          double x1 = 2.0 * _x - _controlX;
          double y1 = 2.0 * _y - _controlY;
          double x2 = (absolute) ? doublet[0].x : _x + doublet[0].x;
          double y2 = (absolute) ? doublet[0].y : _y + doublet[0].y;
          _x = (absolute) ? doublet[1].x : _x + doublet[1].x;
          _y = (absolute) ? doublet[1].y : _y + doublet[1].y;
          _path.cubicTo(
            x1,
            y1,
            _controlX = x2,
            _controlY = y2,
            _x,
            _y,
          );
        }
      }
    
      void _quadratic_bezier_curveto(bool absolute) {
        _scanner.scan(WHITESPACE);
        for (final doublet in _quadratic_bezier_curveto_coordinate_sequence()) {
          double x1 = (absolute) ? doublet[0].x : _x + doublet[0].x;
          double y1 = (absolute) ? doublet[0].y : _y + doublet[0].y;
          _x = (absolute) ? doublet[1].x : _x + doublet[1].x;
          _y = (absolute) ? doublet[1].y : _y + doublet[1].y;
          _path.quadraticBezierTo(
            _controlX = x1,
            _controlY = y1,
            _x,
            _y,
          );
        }
      }
    
      void _smooth_quadratic_bezier_curveto(bool absolute) {
        _scanner.scan(WHITESPACE);
        for (final pair in _coordinate_pair_sequence()) {
          double x1 = 2.0 * _x - _controlX;
          double y1 = 2.0 * _y - _controlY;
          _x = (absolute) ? pair.x : _x + pair.x;
          _y = (absolute) ? pair.y : _y + pair.y;
          _path.quadraticBezierTo(
            _controlX = x1,
            _controlY = y1,
            _x,
            _y,
          );
        }
      }
    
      void _elliptical_arc(bool absolute) {
        _scanner.scan(WHITESPACE);
        for (final arc in _elliptical_arc_argument_sequence()) {
          _x = (absolute) ? arc.xy.x : _x + arc.xy.x;
          _y = (absolute) ? arc.xy.y : _y + arc.xy.y;
          _path.arcToPoint(
            Offset(_controlX = _x, _controlY = _y),
            radius: Radius.elliptical(arc.rx, arc.ry),
            rotation: arc.rot,
            largeArc: arc.large,
            clockwise: arc.sweep,
          );
        }
      }
    
      List<double> _coordinate_sequence() {
        final sequence = [_coordinate()];
        while (!_scanner.isDone && !_scanner.matches(COMMAND)) sequence.add(_coordinate());
        return sequence;
      }
    
      List<_Pair> _coordinate_pair_sequence() {
        final sequence = [_coordinate_pair()];
        while (!_scanner.isDone && !_scanner.matches(COMMAND)) sequence.add(_coordinate_pair());
        return sequence;
      }
    
      List<List<_Pair>> _curveto_coordinate_sequence() {
        final sequence = [_coordinate_pair_triplet()];
        while (!_scanner.isDone && !_scanner.matches(COMMAND)) sequence.add(_coordinate_pair_triplet());
        return sequence;
      }
    
      List<List<_Pair>> _smooth_curveto_coordinate_sequence() {
        final sequence = [_coordinate_pair_double()];
        while (!_scanner.isDone && !_scanner.matches(COMMAND)) sequence.add(_coordinate_pair_double());
        return sequence;
      }
    
      List<List<_Pair>> _quadratic_bezier_curveto_coordinate_sequence() {
        final sequence = [_coordinate_pair_double()];
        while (!_scanner.isDone && !_scanner.matches(COMMAND)) sequence.add(_coordinate_pair_double());
        return sequence;
      }
    
      List<_Arc> _elliptical_arc_argument_sequence() {
        final sequence = [_elliptical_arc_argument()];
        while (!_scanner.isDone && !_scanner.matches(COMMAND)) sequence.add(_elliptical_arc_argument());
        return sequence;
      }
    
      _Arc _elliptical_arc_argument() => _Arc(
            _number(),
            _number(),
            _number(),
            _flag(),
            _flag(),
            _coordinate_pair(),
          );
    
      _Pair _coordinate_pair() => _Pair(
            _coordinate(),
            _coordinate(),
          );
    
      List<_Pair> _coordinate_pair_double() => [
            _coordinate_pair(),
            _coordinate_pair(),
          ];
    
      List<_Pair> _coordinate_pair_triplet() => [
            _coordinate_pair(),
            _coordinate_pair(),
            _coordinate_pair(),
          ];
    
      double _number() {
        _scanner.expect(NUMBER);
        double value = double.parse(_scanner.lastMatch[0]);
        _scanner.scan(COMMA_WHITESPACE);
        return value;
      }
    
      double _coordinate() {
        _scanner.expect(COORDINATE);
        double value = double.parse(_scanner.lastMatch[0]);
        _scanner.scan(COMMA_WHITESPACE);
        return value;
      }
    
      bool _flag() {
        _scanner.expect(FLAG);
        bool value = _scanner.lastMatch[0] == '1';
        _scanner.scan(COMMA_WHITESPACE);
        return value;
      }
    }
    
    class _Pair {
      final double x;
      final double y;
    
      _Pair(this.x, this.y);
    }
    
    class _Arc {
      final double rx;
      final double ry;
      final double rot;
      final bool large;
      final bool sweep;
      final _Pair xy;
    
      _Arc(this.rx, this.ry, this.rot, this.large, this.sweep, this.xy);
    }
    
    // Bare minimum from https://pub.dev/packages/string_scanner
    class _StringScanner {
      final String string;
    
      _StringScanner(this.string);
    
      int _position = 0;
    
      int get position => _position;
    
      set position(int position) {
        if (position < 0 || position > string.length) throw ArgumentError("Invalid position $position");
        _position = position;
        _lastMatch = null;
      }
    
      Match _lastMatch;
    
      Match get lastMatch {
        if (_position != _lastMatchPosition) _lastMatch = null;
        return _lastMatch;
      }
    
      int _lastMatchPosition;
    
      bool get isDone => position == string.length;
    
      bool scan(Pattern pattern) {
        var success = matches(pattern);
        if (success) {
          _position = _lastMatch.end;
          _lastMatchPosition = _position;
        }
        return success;
      }
    
      void expect(Pattern pattern) {
        if (scan(pattern)) return;
        String name = (pattern is RegExp) ? "/${pattern.pattern}/" : '//';
        throw FormatException("expected $name at position $position.");
      }
    
      bool matches(Pattern pattern) {
        _lastMatch = pattern.matchAsPrefix(string, position);
        _lastMatchPosition = _position;
        return _lastMatch != null;
      }
    }

**Comment by dnfield** [comment]
Cool!

I would expect the regexes to be much slower though.  Do you have any benchmarks?

**Comment by deakjahn** [comment]
No, I don't, but I wouldn't worry too much (but it would be nice to measure for sure). Regexes are often compiled to straight code these days and they are very fast for what they can achieve.

But OK, I'm game, I'll make a few tests.

**Comment by deakjahn** [comment]
Here we go. These benchmarks were in debug mode, so JIT instead of AOT, I'd expect the difference to be smaller in release code.

Regex:         Plain:
0:00:00.059384 0:00:00.029513
0:00:00.049952 0:00:00.028444
0:00:00.063663 0:00:00.043434
0:00:00.111749 0:00:00.068494
0:00:00.104056 0:00:00.058688
0:00:00.106258 0:00:00.073148
0:00:00.138766 0:00:00.066935
0:00:00.119845 0:00:00.106167
0:00:00.144371 0:00:00.129637
0:00:00.161709 0:00:00.147501
0:00:00.060613 0:00:00.035779
0:00:00.037753 0:00:00.021809
0:00:00.040637 0:00:00.024722
0:00:00.118033 0:00:00.085325
0:00:00.145045 0:00:00.050024
0:00:00.101073 0:00:00.041973
0:00:00.127164 0:00:00.075437
0:00:00.164756 0:00:00.104413
0:00:00.170583 0:00:00.104195
0:00:00.156534 0:00:00.128251

Some test paths with the parsing run 1,000 times. There is gain but, do to the nature of debug mode, not that consistent. Still, for something that's supposed to run often and maybe repeatedly, it does count. You might want to experiment with it in other settings?

**Comment by deakjahn** [comment]
And the new code: the scanner is less easy to follow, covering up the details is a real advantage of regexes. The upper part is practically the same, though:

    // https://www.w3.org/TR/SVG/paths.html#PathDataBNF
    class SvgPath {
      final String svg;
    
      SvgPath(this.svg);
    
      _StringScanner _scanner;
      Path _path;
      double _x = 0, _y = 0;
      double _controlX = 0, _controlY = 0;
      double _startX = 0, _startY = 0;
    
      Path parse() {
        if (svg == null) return null;
        if (svg.isEmpty) return Path();
    
        _path = Path();
        _scanner = _StringScanner(svg);
        _svg_path();
        return _path;
      }
    
      void _svg_path() {
        _scanner.scanWhitespace();
        while (!_scanner.isDone) {
          int command = _scanner.expectCommand();
          switch (command) {
            case 77: // M
              _moveto(true);
              break;
            case 109: // m
              _moveto(false);
              break;
            case 90: // Z
            case 122: // z
              _closepath();
              break;
            case 76: // L
              _lineto(true);
              break;
            case 108: // l
              _lineto(false);
              break;
            case 72: // H
              _horizontal_lineto(true);
              break;
            case 104: // h
              _horizontal_lineto(false);
              break;
            case 86: // V
              _vertical_lineto(true);
              break;
            case 118: // v
              _vertical_lineto(false);
              break;
            case 67: // C
              _curveto(true);
              break;
            case 99: // c
              _curveto(false);
              break;
            case 83: // S
              _smooth_curveto(true);
              break;
            case 115: // s
              _smooth_curveto(false);
              break;
            case 81: // Q
              _quadratic_bezier_curveto(true);
              break;
            case 113: // q
              _quadratic_bezier_curveto(false);
              break;
            case 84: // T
              _smooth_quadratic_bezier_curveto(true);
              break;
            case 116: // t
              _smooth_quadratic_bezier_curveto(false);
              break;
            case 65: // A
              _elliptical_arc(true);
              break;
            case 97: // a
              _elliptical_arc(false);
              break;
            default:
              throw FormatException('command ${String.fromCharCode(command)}');
          }
        }
      }
    
      void _moveto(bool absolute) {
        _scanner.scanWhitespace();
        for (final pair in _coordinate_pair_sequence()) {
          _x = (absolute) ? pair.x : _x + pair.x;
          _y = (absolute) ? pair.y : _y + pair.y;
          _path.moveTo(
            _startX = _controlX = _x,
            _startY = _controlY = _y,
          );
        }
      }
    
      void _closepath() {
        _scanner.scanWhitespace();
        _x = _controlX = _startX;
        _y = _controlY = _startY;
        _path.close();
      }
    
      void _lineto(bool absolute) {
        _scanner.scanWhitespace();
        for (final pair in _coordinate_pair_sequence()) {
          _x = (absolute) ? pair.x : _x + pair.x;
          _y = (absolute) ? pair.y : _y + pair.y;
          _path.lineTo(
            _controlX = _x,
            _controlY = _y,
          );
        }
      }
    
      void _horizontal_lineto(bool absolute) {
        _scanner.scanWhitespace();
        for (double x in _coordinate_sequence()) {
          _x = (absolute) ? x : _x + x;
          _path.lineTo(
            _controlX = _x,
            _controlY = _y,
          );
        }
      }
    
      void _vertical_lineto(bool absolute) {
        _scanner.scanWhitespace();
        for (double y in _coordinate_sequence()) {
          _y = (absolute) ? y : _y + y;
          _path.lineTo(
            _controlX = _x,
            _controlY = _y,
          );
        }
      }
    
      void _curveto(bool absolute) {
        _scanner.scanWhitespace();
        for (final triplet in _curveto_coordinate_sequence()) {
          double x1 = (absolute) ? triplet[0].x : _x + triplet[0].x;
          double y1 = (absolute) ? triplet[0].y : _y + triplet[0].y;
          double x2 = (absolute) ? triplet[1].x : _x + triplet[1].x;
          double y2 = (absolute) ? triplet[1].y : _y + triplet[1].y;
          _x = (absolute) ? triplet[2].x : _x + triplet[2].x;
          _y = (absolute) ? triplet[2].y : _y + triplet[2].y;
          _path.cubicTo(
            x1,
            y1,
            _controlX = x2,
            _controlY = y2,
            _x,
            _y,
          );
        }
      }
    
      void _smooth_curveto(bool absolute) {
        _scanner.scanWhitespace();
        for (final doublet in _smooth_curveto_coordinate_sequence()) {
          double x1 = 2.0 * _x - _controlX;
          double y1 = 2.0 * _y - _controlY;
          double x2 = (absolute) ? doublet[0].x : _x + doublet[0].x;
          double y2 = (absolute) ? doublet[0].y : _y + doublet[0].y;
          _x = (absolute) ? doublet[1].x : _x + doublet[1].x;
          _y = (absolute) ? doublet[1].y : _y + doublet[1].y;
          _path.cubicTo(
            x1,
            y1,
            _controlX = x2,
            _controlY = y2,
            _x,
            _y,
          );
        }
      }
    
      void _quadratic_bezier_curveto(bool absolute) {
        _scanner.scanWhitespace();
        for (final doublet in _quadratic_bezier_curveto_coordinate_sequence()) {
          double x1 = (absolute) ? doublet[0].x : _x + doublet[0].x;
          double y1 = (absolute) ? doublet[0].y : _y + doublet[0].y;
          _x = (absolute) ? doublet[1].x : _x + doublet[1].x;
          _y = (absolute) ? doublet[1].y : _y + doublet[1].y;
          _path.quadraticBezierTo(
            _controlX = x1,
            _controlY = y1,
            _x,
            _y,
          );
        }
      }
    
      void _smooth_quadratic_bezier_curveto(bool absolute) {
        _scanner.scanWhitespace();
        for (final pair in _coordinate_pair_sequence()) {
          double x1 = 2.0 * _x - _controlX;
          double y1 = 2.0 * _y - _controlY;
          _x = (absolute) ? pair.x : _x + pair.x;
          _y = (absolute) ? pair.y : _y + pair.y;
          _path.quadraticBezierTo(
            _controlX = x1,
            _controlY = y1,
            _x,
            _y,
          );
        }
      }
    
      void _elliptical_arc(bool absolute) {
        _scanner.scanWhitespace();
        for (final arc in _elliptical_arc_argument_sequence()) {
          _x = (absolute) ? arc.xy.x : _x + arc.xy.x;
          _y = (absolute) ? arc.xy.y : _y + arc.xy.y;
          _path.arcToPoint(
            Offset(_controlX = _x, _controlY = _y),
            radius: Radius.elliptical(arc.rx, arc.ry),
            rotation: arc.rot,
            largeArc: arc.large,
            clockwise: arc.sweep,
          );
        }
      }
    
      List<double> _coordinate_sequence() {
        final sequence = [_coordinate()];
        while (!_scanner.isDone && !_scanner.matchesCommand()) sequence.add(_coordinate());
        return sequence;
      }
    
      List<_Pair> _coordinate_pair_sequence() {
        final sequence = [_coordinate_pair()];
        while (!_scanner.isDone && !_scanner.matchesCommand()) sequence.add(_coordinate_pair());
        return sequence;
      }
    
      List<List<_Pair>> _curveto_coordinate_sequence() {
        final sequence = [_coordinate_pair_triplet()];
        while (!_scanner.isDone && !_scanner.matchesCommand()) sequence.add(_coordinate_pair_triplet());
        return sequence;
      }
    
      List<List<_Pair>> _smooth_curveto_coordinate_sequence() {
        final sequence = [_coordinate_pair_double()];
        while (!_scanner.isDone && !_scanner.matchesCommand()) sequence.add(_coordinate_pair_double());
        return sequence;
      }
    
      List<List<_Pair>> _quadratic_bezier_curveto_coordinate_sequence() {
        final sequence = [_coordinate_pair_double()];
        while (!_scanner.isDone && !_scanner.matchesCommand()) sequence.add(_coordinate_pair_double());
        return sequence;
      }
    
      List<_Arc> _elliptical_arc_argument_sequence() {
        final sequence = [_elliptical_arc_argument()];
        while (!_scanner.isDone && !_scanner.matchesCommand()) sequence.add(_elliptical_arc_argument());
        return sequence;
      }
    
      _Arc _elliptical_arc_argument() => _Arc(
            _number(),
            _number(),
            _number(),
            _flag(),
            _flag(),
            _coordinate_pair(),
          );
    
      _Pair _coordinate_pair() => _Pair(
            _coordinate(),
            _coordinate(),
          );
    
      List<_Pair> _coordinate_pair_double() => [
            _coordinate_pair(),
            _coordinate_pair(),
          ];
    
      List<_Pair> _coordinate_pair_triplet() => [
            _coordinate_pair(),
            _coordinate_pair(),
            _coordinate_pair(),
          ];
    
      double _number() {
        double value = _scanner.expectNumber();
        _scanner.scanCommaWhitespace();
        return value;
      }
    
      double _coordinate() {
        double value = _scanner.expectCoordinate();
        _scanner.scanCommaWhitespace();
        return value;
      }
    
      bool _flag() {
        bool value = _scanner.expectFlag();
        _scanner.scanCommaWhitespace();
        return value;
      }
    }
    
    class _Pair {
      final double x;
      final double y;
    
      _Pair(this.x, this.y);
    }
    
    class _Arc {
      final double rx;
      final double ry;
      final double rot;
      final bool large;
      final bool sweep;
      final _Pair xy;
    
      _Arc(this.rx, this.ry, this.rot, this.large, this.sweep, this.xy);
    }
    
    class _StringScanner {
      final String string;
    
      _StringScanner(this.string);
    
      int _position = 0;
    
      bool get isDone => _position == string.length;
    
      int get _nextChar => isDone ? null : string.codeUnitAt(_position);
    
      bool _isWhitespace(int char) =>
          char == 9 || // tab
          char == 10 || // carriage return
          char == 12 || // form feed
          char == 13 || // line feed
          char == 32; // space
    
      bool _isCommaWhitespace(int char) =>
          char == 44 || // comma
          _isWhitespace(char);
    
      void scanWhitespace() {
        while (!isDone && _isWhitespace(_nextChar)) _position++;
      }
    
      void scanCommaWhitespace() {
        if (_isCommaWhitespace(_nextChar)) {
          _position++;
          while (!isDone && _isCommaWhitespace(_nextChar)) _position++;
        }
      }
    
      bool _isCommand(int char) =>
          char == 77 || // M
          char == 109 || // m
          char == 90 || // Z
          char == 122 || // z
          char == 76 || // L
          char == 108 || // l
          char == 72 || // H
          char == 104 || // h
          char == 86 || // V
          char == 118 || // v
          char == 67 || // C
          char == 99 || // c
          char == 83 || // S
          char == 115 || // s
          char == 81 || // Q
          char == 113 || // q
          char == 84 || // T
          char == 116 || // t
          char == 65 || // A
          char == 97; // a
    
      int expectCommand() {
        int char = _nextChar;
        if (_isCommand(char)) {
          _position++;
          return char;
        } else
          throw FormatException("expected command at position $_position.");
      }
    
      bool matchesCommand() {
        return _isCommand(_nextChar);
      }
    
      bool _isFlag(int char) =>
          char == 48 || // 0
          char == 49; // 1
    
      bool expectFlag() {
        int char = _nextChar;
        if (_isFlag(char)) {
          _position++;
          return char == 49;
        } else
          throw FormatException("expected command at position $_position.");
      }
    
      bool _isSign(int char) =>
          char == 43 || // plus
          char == 45; // minus
    
      bool _isDecimal(int char) => char == 46; // period
    
      bool _isDigit(int char) => char >= 48 && char <= 57; // 0..9
    
      bool decimalFound;
    
      bool _isDecimalDigit(int char) {
        if (decimalFound)
          return (_isDigit(char));
        else {
          if (_isDecimal(char)) {
            decimalFound = true;
            return true;
          } else
            return (_isDigit(char));
        }
      }
    
      double expectNumber() {
        final s = StringBuffer();
        int char;
        decimalFound = false;
        while (!isDone && _isDecimalDigit(char = _nextChar)) {
          _position++;
          s.writeCharCode(char);
        }
        if (s.isEmpty)
          throw FormatException("expected unsigned number at position $_position.");
        else
          return double.parse(s.toString());
      }
    
      double expectCoordinate() {
        final s = StringBuffer();
        int char = _nextChar;
        if (_isSign(char)) {
          _position++;
          s.writeCharCode(char);
        }
        decimalFound = false;
        while (!isDone && _isDecimalDigit(char = _nextChar)) {
          _position++;
          s.writeCharCode(char);
        }
        if (s.isEmpty)
          throw FormatException("expected signed number at position $_position.");
        else
          return double.parse(s.toString());
      }
    }

**Comment by dnfield** [comment]
I might be reading this wrong, but it looks like it takes about twice as long in many of those cases...  It's also not clear to me what you're actually testing without the code.

**Comment by deakjahn** [comment]
Yes, in the debug regime it looks like mostly double, although if you compare some of those items, sometimes it goes down to much less than that.

These were simple paths, from polygons, hexagons or multi-pointed stars up to some icons. What I measured was the execution time of 1000 runs, like this:

    Path path;
    final stopwatch = Stopwatch()..start();
    for (int i = 0; i < 1000; i++) path = SvgPath(curve).parse();
    print('parse executed in ${stopwatch.elapsed}');

before and after.

**Comment by dnfield** [comment]
The code has significantly changed at this point, and we never quite got to benchmarks that showed an improvement here. Closing this.
